# These are supported funding model platforms

github: # [@TRISTAN](https://github.com/Tristan7122) 
buy_me_a_coffee: # wa.me/27634624586 
thanks_dev: # https://github.com/Tristan7122
custom: # https://chat.whatsapp.com/IMF1LrcOE828VlnFCSZTtH 
